version: '3.8'

services:
  backend:
    image: unittcms-backend:latest
    build:
      context: ./backend
    ports:
      - '7001:7001'
    environment:
      - NODE_ENV=production
      - FRONTEND_ORIGIN=https://7000--main--cuong--cuong-admin.coder1.hirogo-dev.com
      - PORT=7001
    volumes:
      - ./db-data:/app/database

  frontend:
    image: unittcms-frontend:latest
    build:
      context: ./frontend
    ports:
      - '7000:7000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_ORIGIN=https://7001--main--cuong--cuong-admin.coder1.hirogo-dev.com
      - PORT=7000
    depends_on:
      - backend